### ISSUE TITLE
Ambiguity in uf2families.json for STM32F4 processors

### ISSUE THREAD

**Issue by NathanY3G** [microsoft/uf2#64]
The `uf2families.json` file contains multiple IDs relating to `STM32F4` processors - 1 for the entire *series* and 2 relating to the `STM32F407` product line within that series. However, the description for the entire series is `ST STM32F401` which I believe is incorrect! This appears to have caused some confusion in two related open source projects where different IDs have been used for the `STM32F405`. I would like to propose changing the description to try and improve the situation.

```
   {
        "id": "0x57755a57",
        "short_name": "STM32F4",
        "description": "ST STM32F4xx"
    },
```

For reference:
https://www.st.com/content/ccc/fragment/product_related/series_information/series_level_diagram/group0/6e/ab/f8/ba/9c/9a/4d/37/obn_stm32f4_series_ss1577/files/obn_stm32f4_series_ss1577.jpg/jcr:content/translations/en.obn_stm32f4_series_ss1577.jpg

**Comment by mmoskal** [comment]
Thank you, I guess this description is better.

The problem is the usage here really depends on how you build your binary. It could be that the same binary works on all STM32F4 boards, or it could be that it only works on say STM32401RE with a particular pinout.

Bootloaders are free to accept any number of IDs though!

**Comment by NathanY3G** [comment]
Thank you @mmoskal for both the tweak and more information about UF2. It is appreciated!
